version: 1
public_repo: airnub/agentic-delivery-framework
default_branch: main

allow:
  - README.md
  - docs/**            # Markdown, images, PDFs, CSVs, etc.
  - website/**         # Docusaurus site code (docs-only code is OK)
  - .github/workflows/docs.yml

deny:
  - .github/**         # deny all workflows...
  - scripts/**         # ...then re-allow the single docs.yml above
  - tools/**
  - internal/**
  - private/**
  - **/drafts/**
  - **/pre-release/**
  - **/*.env*
  - **/.git*
  - Dockerfile*
  - docker-compose*.yml
