name: Docs (Docusaurus → GitHub Pages)

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: github.repository == 'airnub/agentic-delivery-framework' # inert on internal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install deps
        working-directory: website
        run: |
          npm ci || npm i

      - name: Build (PUBLIC)
        env:
          SITE_PROFILE: public
        working-directory: website
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy:
    if: github.repository == 'airnub/agentic-delivery-framework'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
