name: docs-preview-internal

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/docs-preview-internal.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-preview-internal-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Install dependencies
        working-directory: website
        run: npm ci
      - name: Build internal preview
        working-directory: website
        env:
          SITE_PROFILE: internal
        run: npm run build
      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-internal-preview
          path: website/build
          if-no-files-found: error

# This work is licensed under CC BY-SA 4.0.
