name: license-notice-check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Ensure CC BY-SA notice exists on Markdown and YAML files
        run: |
          set -euo pipefail
          license_line="This work is licensed under CC BY-SA 4.0."
          missing_files=""
          while IFS= read -r file; do
            if [ -z "$file" ]; then
              continue
            fi
            case "$file" in
              .github/ISSUE_TEMPLATE/*|.github/PULL_REQUEST_TEMPLATE.md)
                continue
                ;;
            esac
            if ! grep -Fq "$license_line" "$file"; then
              missing_files+="$file\n"
            fi
          done < <(git ls-files '*.md' '*.yml' '*.yaml')
          if [ -n "$missing_files" ]; then
            printf '::error::The following files are missing the CC BY-SA license notice:%s' "\n"
            printf '%s' "$missing_files"
            exit 1
          fi
          echo "All Markdown and YAML files include the CC BY-SA license notice."
# This work is licensed under CC BY-SA 4.0.
